[package]
name = "repox"
version = "0.1.0"
edition = "2024"
authors = ["Ben Falk <benjamin.falk@yahoo.com>"]
description = "trait framework for data repository patterns"
repository = "https://benfalk.github.io/repox/"
license = "MIT"
keywords = ["repository", "data-access", "framework"]
categories = ["database-implementations", "database"]

[features]
default = ["derive"]
mock = ["dep:mockall", "repox_derive/mock"]
derive = ["repox_derive"]

[dependencies]
thiserror.workspace = true
anyhow.workspace = true
mockall = { workspace = true, optional = true }

[dependencies.repox_derive]
path = "../repox_derive"
optional = true
version = "0.1.0"

[dev-dependencies]
dashmap = { workspace = true }
pollster = { workspace = true }
